name: Test code - pytests

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ['3.x', '3.8']
    
    runs-on: ${{ matrix.platform }}
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    
    - name: Install pytests
      run: |
        pip3 install pytest pytest_mock

    - name: Test
      run: |
        ls -la
        pytest test_policy.py -v
